services:
  sparkle-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1330:3000"
    environment:
      - PUBLIC_HOST=https://wuw.lyu.sh
      - PUBLIC_WS=wss://wuw.lyu.sh
