export type CueForgeLanguage = {
	ids: readonly string[];
	name: string;
};

export const cueForgeLanguages = [
	{ ids: ['eng', 'en'], name: 'English' },
	{ ids: ['chi', 'zho', 'zh', 'zh-hans', 'zh-cn', 'zh-sg', 'cmn'], name: 'SIMPLIFIED Chinese' },
	{ ids: ['zht', 'zh-hant', 'zh-tw', 'zh-hk', 'zh-mo'], name: 'TRADITIONAL Chinese' },
	{ ids: ['spa', 'es'], name: 'Spanish' },
	{ ids: ['hin', 'hi'], name: 'Hindi' },
	{ ids: ['arb'], name: 'Modern Standard Arabic' },
	{ ids: ['ara', 'ar'], name: 'Arabic' },
	{ ids: ['fre', 'fra', 'fr'], name: 'French' },
	{ ids: ['ben', 'bn'], name: 'Bengali' },
	{ ids: ['por', 'pt'], name: 'Portuguese' },
	{ ids: ['ind', 'id'], name: 'Indonesian' },
	{ ids: ['urd', 'ur'], name: 'Urdu' },
	{ ids: ['rus', 'ru'], name: 'Russian' },
	{ ids: ['ger', 'deu', 'de'], name: 'German' },
	{ ids: ['jpn', 'ja'], name: 'Japanese' },
	{ ids: ['pcm'], name: 'Nigerian Pidgin' },
	{ ids: ['arz'], name: 'Egyptian Arabic' },
	{ ids: ['mar', 'mr'], name: 'Marathi' },
	{ ids: ['vie', 'vi'], name: 'Vietnamese' },
	{ ids: ['tel', 'te'], name: 'Telugu' },
	{ ids: ['swa', 'swh', 'sw'], name: 'Swahili' },
	{ ids: ['hau', 'ha'], name: 'Hausa' },
	{ ids: ['tur', 'tr'], name: 'Turkish' },
	{ ids: ['pnb'], name: 'Western Punjabi' },
	{ ids: ['pan', 'pa'], name: 'Punjabi' },
	{ ids: ['tgl', 'tl'], name: 'Tagalog' },
	{ ids: ['fil'], name: 'Filipino' },
	{ ids: ['tam', 'ta'], name: 'Tamil' },
	{ ids: ['yue'], name: 'Yue Chinese' },
	{ ids: ['wuu'], name: 'Wu Chinese' },
	{ ids: ['pes', 'fas', 'per', 'fa'], name: 'Persian' },
	{ ids: ['kor', 'ko'], name: 'Korean' },
	{ ids: ['may', 'msa', 'ms'], name: 'Malay' },
	{ ids: ['amh', 'am'], name: 'Amharic' },
	{ ids: ['tha', 'th'], name: 'Thai' },
	{ ids: ['jav', 'jv'], name: 'Javanese' },
	{ ids: ['ita', 'it'], name: 'Italian' },
	{ ids: ['guj', 'gu'], name: 'Gujarati' },
	{ ids: ['kan', 'kn'], name: 'Kannada' },
	{ ids: ['apc'], name: 'Levantine Arabic' },
	{ ids: ['apd'], name: 'Sudanese Arabic' },
	{ ids: ['yor', 'yo'], name: 'Yoruba' },
	{ ids: ['bho'], name: 'Bhojpuri' },
	{ ids: ['mal', 'ml'], name: 'Malayalam' },
	{ ids: ['pol', 'pl'], name: 'Polish' },
	{ ids: ['pus', 'ps'], name: 'Pashto' },
	{ ids: ['nan'], name: 'Min Nan Chinese' },
	{ ids: ['hak'], name: 'Hakka Chinese' },
	{ ids: ['cjy'], name: 'Jinyu Chinese' },
	{ ids: ['rom'], name: 'Romani' },
	{ ids: ['arq'], name: 'Algerian Arabic' },
	{ ids: ['hsn'], name: 'Xiang Chinese' },
	{ ids: ['raj'], name: 'Rajasthani' },
	{ ids: ['ory', 'or'], name: 'Odia' },
	{ ids: ['mai'], name: 'Maithili' },
	{ ids: ['mya', 'bur', 'my'], name: 'Burmese' },
	{ ids: ['sun', 'su'], name: 'Sundanese' },
	{ ids: ['ary'], name: 'Moroccan Arabic' },
	{ ids: ['uzb', 'uz'], name: 'Uzbek' },
	{ ids: ['ibo', 'ig'], name: 'Igbo' },
	{ ids: ['nqo'], name: "N'Ko" },
	{ ids: ['ukr', 'uk'], name: 'Ukrainian' },
	{ ids: ['uzn'], name: 'Northern Uzbek' },
	{ ids: ['snd', 'sd'], name: 'Sindhi' },
	{ ids: ['rum', 'ron', 'ro'], name: 'Romanian' },
	{ ids: ['ful', 'ff'], name: 'Fula' },
	{ ids: ['orm', 'om'], name: 'Oromo' },
	{ ids: ['dut', 'nld', 'nl'], name: 'Dutch' },
	{ ids: ['aze', 'az'], name: 'Azerbaijani' },
	{ ids: ['aec'], name: 'Saidi Arabic' },
	{ ids: ['gan'], name: 'Gan Chinese' },
	{ ids: ['awa'], name: 'Awadhi' },
	{ ids: ['kur', 'ku'], name: 'Kurdish' },
	{ ids: ['pbu'], name: 'Northern Pashto' },
	{ ids: ['mag'], name: 'Magahi' },
	{ ids: ['skr'], name: 'Saraiki' },
	{ ids: ['lin', 'ln'], name: 'Lingala' },
	{ ids: ['hbs', 'sh'], name: 'Serbo-Croatian' },
	{ ids: ['mlg', 'mg'], name: 'Malagasy' },
	{ ids: ['tzm'], name: 'Central Atlas Tamazight' },
	{ ids: ['khm', 'km'], name: 'Khmer' },
	{ ids: ['hne'], name: 'Chhattisgarhi' },
	{ ids: ['som', 'so'], name: 'Somali' },
	{ ids: ['tuk', 'tk'], name: 'Turkmen' },
	{ ids: ['zha', 'za'], name: 'Zhuang' },
	{ ids: ['ceb'], name: 'Cebuano' },
	{ ids: ['nep', 'ne'], name: 'Nepali' },
	{ ids: ['acm'], name: 'Mesopotamian Arabic' },
	{ ids: ['sin', 'si'], name: 'Sinhala' },
	{ ids: ['asm', 'as'], name: 'Assamese' },
	{ ids: ['tts'], name: 'Isan' },
	{ ids: ['kau', 'kr'], name: 'Kanuri' },
	{ ids: ['mad'], name: 'Madurese' },
	{ ids: ['gre', 'ell', 'el'], name: 'Greek' },
	{ ids: ['kmr'], name: 'Kurmanji' },
	{ ids: ['fuv'], name: 'Nigerian Fulfulde' },
	{ ids: ['acw'], name: 'Hijazi Arabic' },
	{ ids: ['bar'], name: 'Bavarian' },
	{ ids: ['tgk', 'tg'], name: 'Tajik' },
	{ ids: ['bgc'], name: 'Haryanvi' },
	{ ids: ['mwr'], name: 'Marwari' },
	{ ids: ['syl'], name: 'Sylheti' },
	{ ids: ['azb'], name: 'South Azerbaijani' },
	{ ids: ['ctg'], name: 'Chittagonian' },
	{ ids: ['tso', 'ts'], name: 'Tsonga' },
	{ ids: ['kaz', 'kk'], name: 'Kazakh' },
	{ ids: ['hun', 'hu'], name: 'Hungarian' },
	{ ids: ['zul', 'zu'], name: 'Zulu' },
	{ ids: ['kin', 'rw'], name: 'Kinyarwanda' },
	{ ids: ['nya', 'ny'], name: 'Chichewa' },
	{ ids: ['cze', 'ces', 'cs'], name: 'Czech' },
	{ ids: ['dan', 'da'], name: 'Danish' },
	{ ids: ['fin', 'fi'], name: 'Finnish' },
	{ ids: ['heb', 'he'], name: 'Hebrew' },
	{ ids: ['nor', 'no'], name: 'Norwegian' },
	{ ids: ['swe', 'sv'], name: 'Swedish' }
] as const satisfies readonly CueForgeLanguage[];

export function normalizeLanguageId(id: string) {
	return id.trim().toLowerCase();
}

export const cueForgeLanguageNameById = Object.freeze(
	cueForgeLanguages.reduce<Record<string, string>>((acc, language) => {
		for (const id of language.ids) {
			acc[normalizeLanguageId(id)] = language.name;
		}
		return acc;
	}, {})
);

export function getCueForgeLanguageName(id: string) {
	return cueForgeLanguageNameById[normalizeLanguageId(id)] || '';
}
