import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = path.join(root, 'public');
const buildDir = path.resolve(root, process.env.SPARKLE_BUILD_DIR || '.next');
const devWorker = `// Generated by scripts/generate-sw.mjs --dev. Development always uses the network.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
 event.waitUntil((async () => {
  await Promise.all((await caches.keys()).filter((name) => name.startsWith('sparkle-')).map((name) => caches.delete(name)));
  await self.clients.claim();
  await self.registration.unregister();
 })());
});
`;

if (process.argv.includes('--dev')) {
	await writeFile(
		path.join(publicDir, 'sw.js'),
		await format(devWorker, {
			parser: 'babel',
			useTabs: true,
			singleQuote: true,
			trailingComma: 'none',
			printWidth: 100
		})
	);
} else {
	// Fail if there is no completed build; never publish a timestamp-only fallback.
	const buildId = (await readFile(path.join(buildDir, 'BUILD_ID'), 'utf8')).trim();
	const extensions = new Set([
		'.css',
		'.gif',
		'.ico',
		'.jpeg',
		'.jpg',
		'.js',
		'.json',
		'.png',
		'.svg',
		'.ttf',
		'.otf',
		'.wasm',
		'.webmanifest',
		'.webp',
		'.woff',
		'.woff2',
		'.mp3',
		'.ogg',
		'.wav'
	]);
	const assets = {};
	async function collect(directory, prefix) {
		for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) =>
			a.name.localeCompare(b.name)
		)) {
			if (entry.name === '_sparkle' || entry.name === 'sw.js') continue;
			const absolute = path.join(directory, entry.name);
			const url = `${prefix}/${encodeURIComponent(entry.name)}`;
			if (entry.isDirectory()) await collect(absolute, url);
			else if (
				entry.isFile() &&
				(extensions.has(path.extname(entry.name)) || url === '/offline.html')
			) {
				const bytes = await readFile(absolute);
				assets[url] = {
					revision: createHash('sha256').update(bytes).digest('hex'),
					size: bytes.length
				};
			}
		}
	}
	await collect(publicDir, '');
	await collect(path.join(buildDir, 'static'), '/_next/static');
	const manifest = JSON.stringify({ buildId, assets });
	const worker = `// Build ${JSON.stringify(buildId)}\n${await readFile(path.join(root, 'scripts/service-worker.js'), 'utf8')}`;
	// next start reads public; the standalone/Docker server reads standalone/public.
	for (const target of [publicDir, path.join(buildDir, 'standalone', 'public')]) {
		await mkdir(path.join(target, '_sparkle'), { recursive: true });
		await writeFile(path.join(target, '_sparkle', 'sw.js'), worker);
		await writeFile(path.join(target, '_sparkle', 'assets.json'), manifest);
	}
	console.log(
		`Generated production worker and ${Object.keys(assets).length} asset revisions for ${buildId}.`
	);
}
